### ISSUE TITLE
Bug: Log Formatter throws Error & Breaks Lambda: Class constructor LogFormatter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-powertools/powertools-lambda-typescript#1832]
### Expected Behaviour

Update: I solved it by changing the target and lib in `tsconfig`.

By following [the example](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#custom-log-formatter-bring-your-own-formatter) of bringing my own log formatter I expect that my own log formatter is applied.

### Current Behaviour

The Lambda function where I'm using my logger breaks and throws the error:

```
2023-12-23T07:12:11.030Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "Class constructor LogFormatter cannot be invoked without 'new'",
    "stack": [
        "TypeError: Class constructor LogFormatter cannot be invoked without 'new'",
        "    at new MyCompanyLogFormatter (/var/task/out/utils/log-formatter.js:23:42)",
        "    at Object.<anonymous> (/var/task/out/utils/logger.js:10:19)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
        "    at Module._load (node:internal/modules/cjs/loader:960:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
        "    at require (node:internal/modules/cjs/helpers:119:18)",
        "    at Object.<anonymous> (/var/task/out/adapter/dynamodb/dynamodb.adapter.js:43:16)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)"
    ]
}
```

### Code snippet

File: `backend/lambda/utils/logger.ts` -> Logger that is exported and shared in other files

```ts
import { Logger } from "@aws-lambda-powertools/logger";
import { MyCompanyLogFormatter } from "./log-formatter";

export const logger = new Logger({
  sampleRateValue: 0.1,
  serviceName: "repo-tracker",
  logFormatter: new MyCompanyLogFormatter(),
});

```

File: `backend/lambda/utils/log-formatter.ts` -> Log Formatter taken from documentation page

```ts
import { LogFormatter } from "@aws-lambda-powertools/logger";
import {
  LogAttributes,
  UnformattedAttributes,
} from "@aws-lambda-powertools/logger/lib/types";

// Replace this line with your own type
type MyCompanyLog = LogAttributes;

class MyCompanyLogFormatter extends LogFormatter {
  public formatAttributes(attributes: UnformattedAttributes): MyCompanyLog {
    return {
      message: attributes.message,
      service: attributes.serviceName,
      environment: attributes.environment,
      awsRegion: attributes.awsRegion,
      correlationIds: {
        awsRequestId: attributes.lambdaContext?.awsRequestId,
        xRayTraceId: attributes.xRayTraceId,
      },
      lambdaFunction: {
        name: attributes.lambdaContext?.functionName,
        arn: attributes.lambdaContext?.invokedFunctionArn,
        memoryLimitInMB: attributes.lambdaContext?.memoryLimitInMB,
        version: attributes.lambdaContext?.functionVersion,
        coldStart: attributes.lambdaContext?.coldStart,
      },
      logLevel: attributes.logLevel,
      timestamp: this.formatTimestamp(attributes.timestamp), // You can extend this function
      logger: {
        sampleRateValue: attributes.sampleRateValue,
      },
    };
  }
}

export { MyCompanyLogFormatter };

```

### Steps to Reproduce

1. Create the custom log formatter like in [this example](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#custom-log-formatter-bring-your-own-formatter)
2. Create a logger by instantiating the new log formatter
3. Deploy

### Possible Solution

Old `tsconfig`

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es2015", "es2015.promise", "dom"],
    "outDir": "./out",
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["lambda/**/*.ts"],
  "exclude": ["node_modules"]
}
```

`tsconfig` that solves the problem:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2021",
    "lib": ["es2021"],
    "outDir": "./out",
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["lambda/**/*.ts"],
  "exclude": ["node_modules"]
}

```

### Powertools for AWS Lambda (TypeScript) version

1.17.0

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by am29d** [comment]
Hey @AlessandroVol23 , sorry for the late reply. Is it still a bug on our side or is it resolved with using `es2021` ?

**Comment by AlessandroVol23** [comment]
No worries! This is resolved with `es2021`. Not sure if we should note that somewhere. Because of me we can close this issue 😊

Thanks!
