### ISSUE TITLE
Feature request: Support LLRT (Low Latency Runtime)

### ISSUE THREAD

**Issue by NimmLor** [aws-powertools/powertools-lambda-typescript#2050]
### Use case

This feature request is about the beta of the new lightweight JavaScript runtime [LLRT (Low Latency Runtime)](https://github.com/awslabs/llrt).

Currently, the Logger crashes when importing the "console" module.

Demo repository: https://github.com/NimmLor/aws-cdk-llrt-demo

```json
{
  "errorType": "ReferenceError",
  "errorMessage": "Error resolving module '/var/task/console' from '/var/task/index.js'",
  "stackTrace": [
    "    at ../../node_modules/@aws-lambda-powertools/logger/lib/Logger.js (/var/task/index.js:1652:26)",
    "    at __require2 (/var/task/index.js:15:17)",
    "    at ../../node_modules/@aws-lambda-powertools/logger/lib/index.js (/var/task/index.js:2555:18)",
    "    at __require2 (/var/task/index.js:15:17)",
    "    at <anonymous> (/var/task/index.js:2562:29)",
    ""
  ]
}
```

```js
// esbuild output, failing code snippet

/** ... **/
var require_Logger = __commonJS({
  "../../node_modules/@aws-lambda-powertools/logger/lib/Logger.js"(exports) {
    "use strict";
    var __importDefault = exports && exports.__importDefault || function(mod) {
      return mod && mod.__esModule ? mod : { "default": mod };
    };
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Logger = void 0;
    var node_crypto_1 = __require("crypto");
    var node_console_1 = __require("console");
/** ... **/
```

```ts
// index.ts

import { Logger } from '@aws-lambda-powertools/logger'

export const handler = async () => {
  const logger = new Logger()
  logger.info('Hello world')

  return {
    body: JSON.stringify({
      hello: 'world',
    }),
    statusCode: 200,
  }
}
``` 

### Solution/User Experience

> LLRT offers up to over 10x faster startup and up to 2x overall lower cost compared to other JavaScript runtimes running on AWS Lambda

It would be great if the aws-lambda-powertools would support this runtime,  usage should be exactly the same as for nodejs runtimes.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hey @NimmLor ,

thanks for raising the issue. This is strange, folling the [compatibility matrix](https://github.com/awslabs/llrt?tab=readme-ov-file#compatibility-matrix) of LLRT, both crypto and node are supported. Can you provide more information on the Lambda settings and how you packaged the code (versions, package.json, any relevant tools used). 

Happy to look into the issue and bring Powertools to LLRT.

**Comment by NimmLor** [comment]
Hi @am29d,

I've quickly setup a demo repository for testing the LLRT with AWS CDK.

https://github.com/NimmLor/aws-cdk-llrt-demo

**Comment by am29d** [comment]
I tried the example and something is odd with the LLRT, @dreamorosi was faster than me to open an issue in their repo.

**Comment by dreamorosi** [comment]
Hi, I am able to reproduce the error you showed in the initial post but the issue is with LLRT rather than with Powertools.

As you mentioned, the code throws an error when importing the `console` module. To reproduce the issue I deployed a function with the following code, which as you can see doesn't have anything Powertools specific:

```ts
import { Console } from "node:console";

const con = new Console({ stdout: process.stdout, stderr: process.stderr });

export const handler = async (event: any) => {
  con.log("Hello, world!");
  return "Hello, world!";
};
```

Once deployed using the [`cdk-lambda-llrt`](https://github.com/tmokmss/cdk-lambda-llrt/tree/main) construct, I get the same exact error:

```
  24-02-12T15:15:47.833Z        n/a     ERROR   ReferenceError: Error resolving module 'console' from '/var/task/index.mjs'
} stackTrace: [ '' ]or resolving module 'console' from '/var/task/index.mjs'',
INIT_REPORT Init Duration: 40.23 ms     Phase: init     Status: error   Error Type: Runtime.ExitError
  24-02-12T15:15:48.350Z        n/a     ERROR   ReferenceError: Error resolving module 'console' from '/var/task/index.mjs'
} stackTrace: [ '' ]or resolving module 'console' from '/var/task/index.mjs'',
INIT_REPORT Init Duration: 523.69 ms    Phase: invoke   Status: error   Error Type: Runtime.ExitError
START RequestId: 36e99bfc-806a-4326-963b-354ee212c545 Version: $LATEST
END RequestId: 36e99bfc-806a-4326-963b-354ee212c545
REPORT RequestId: 36e99bfc-806a-4326-963b-354ee212c545  Duration: 551.40 ms     Billed Duration: 551 ms Memory Size: 128 MB     Max Memory Used: 21 MB  Status: error      Error Type: Runtime.ExitError
```

After taking a look at the LLRT repo, and in light of this error, I think the [compatibility matrix](https://github.com/awslabs/llrt?tab=readme-ov-file#compatibility-matrix) might be wrong. The table lists the `console` module as supported, however their [API documentation](https://github.com/awslabs/llrt/blob/main/API.md) doesn't include it anywhere.

I have opened an issue on their repo so that they can confirm whether the module is expected to work or not, and if not, to ask whether there's any chance that it will be implemented.

As a side note, I want to remark that according to both our tenets ([see first point](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)) and versioning policy (see [dependency lifecycle section](https://docs.powertools.aws.dev/lambda/typescript/latest/versioning/#dependency-lifecycle)) our current priority is to officially support AWS Lambda managed runtimes - aka `nodejs16x`, `nodejs18x`, and `nodejs20x` at the time of writing.

LLRT has been met with remarkable positive feedback and shows a lot of promise, however while we are excited about it and eager to see where it goes, making significant changes to Powertools to support it would be premature since LLRT itself is considered experimental and subject to change.

With that said, we are open to work with the LLRT team to fix this specific issue, and other similar ones where LLRT is missing support for common Node.js APIs. Likewise, we are open to consider making changes on our side only as long as they don't impact compatibility, DX, and performance with the main Node.js runtimes.

**Comment by perpil** [comment]
Not sure if this helps, but at least for the Metrics package, if I patch it to lazy-load `node:console` and set the `POWERTOOLS_DEV` env environment variable to `true`, metrics appear to work.

I removed the `const node_console_1 = require("node:console");` from the top of the compiled ts file at: `node_modules/@aws-lambda-powertools/metrics/lib/Metrics.js` and updated the setConsole method to:
```js
    setConsole() {
        if (!this.getEnvVarsService().isDevMode()) {
            const node_console_1 = require("node:console");
            this.console = new node_console_1.Console({
                stdout: process.stdout,
                stderr: process.stderr,
            });
        }
        else {
            this.console = console;
        }
    }
```

**Comment by dreamorosi** [comment]
Hi @perpil thank you for chiming in. Indeed making the import lazy and bypassing the logic that uses it via the `POWERTOOLS_DEV` variable helps remove the issue. Thank you for confirming that this would be the only blocker for Logger to work on LLRT.

While it's a solution, this is not the kind of DX we are aiming for, so I would still consider the lack of `console` a blocker and push for it to be included in the runtime.

To this end, I'd appreciate your 👍 or comment on the linked issue if you'd like LLRT to improve compatibility with Powertools, that'd help to give more weight to the request.

**Comment by dreamorosi** [comment]
According to awslabs/llrt#130 partial support for `Console` module has been added to LLRT. This would allow Logger & Metrics to work with the runtime without any patching.

As soon as they make a release and I can test the change I'll do so and report back here.

**Comment by dreamorosi** [comment]
LLRT have released a new beta version and the issue with `Console` went away, however we now have another missing API.

I have opened an issue on their repo to track this: awslabs/llrt#302

LLRT also have opened an issue to track support for Powertools in general, which you can find here: awslabs/llrt#251

**Comment by NimmLor** [comment]
Hi, as mentioned above, `node:util` is only used once in the entire codebase and can easily be replaced by a template literal to allow us to use the logger for now.

**Comment by dreamorosi** [comment]
Thanks for opening the PR, I left some more comments there on why I was reticent to remove it but on second thought I think it's safe to use template literals and remove the blocker.

I have modified/commented on the LLRT repo about the change on our side.

As far as I can tell we're still missing the `randomInt` API from `node:crypto` which was merged in awslabs/llrt#306 but not yet released.

Once LLRT releases the next beta, I'll test the Logger and see if we have everything. If anyone does it first I'd appreciate if they could report here.

**Comment by perpil** [comment]
Seems like the PR's for supporting console, switching to template literals and crypto.randInt are now resolved, is there anything remaining here?

**Comment by NimmLor** [comment]
> Seems like the PR's for supporting console, switching to template literals and crypto.randInt are now resolved, is there anything remaining here?

The logger should be working as expected.

When I tried the tracer the last time and analyzed the bundle I notized the following `node:xxxxx` deps used in the esbuild output:

- `util`
- `assert`
- `async_hooks`
- `dgram`
- `fs`
- `http`
- `os`
- `querystring`
- `url`

However it's very likely that most of these were imported in [aws-xray-sdk-core](https://github.com/aws/aws-xray-sdk-node/)

**Comment by dreamorosi** [comment]
Yep, Tracer is the one lagging behind among the three core utilities, but no because of LLRT fault. All the modules mentioned come from AWS X-Ray SDK and for a number of reasons I don't expect LLRT to prioritize them in the short term.

Logger and Metrics work without any issue on LLRT, and the same goes for Batch Processing.

**Comment by perpil** [comment]
In PowerTools Metrics 2.12 [`isDate`](https://github.com/aws-powertools/powertools-lambda-typescript/blame/cbe5ccb448550b046fea6aeecef0b9c4a17d1584/packages/metrics/src/Metrics.ts#L2) is not available in llrt 0.4-0-beta. I was able to patch around it, but surfacing for visibility.

**Comment by dreamorosi** [comment]
Hi @perpil, thank you for reporting this.

I'm going to open a PR to phase out the usage of `isDate` in favor of a simpler `instanceof Date` which should be supported by LLRT as a global.

The change will land in our next release, so you can probably remove the patch on your side once you upgrade.

**Comment by nabetti1720** [comment]
Any new information on how well it's working at the moment?

I was able to confirm that I could import everything except `Tracer` on my laptop, but I don't have a specific use case, so I can't confirm whether it works as you expect...

**Comment by perpil** [comment]
@nabetti1720 I resolved #4499 thanks to your work that made it into LLRT 0.7.0-beta. Supporting Tracer is a lower priority than the core functionality.

**Comment by dreamorosi** [comment]
Does LLRT support response streaming like the [managed Node.js runtimes](https://docs.aws.amazon.com/lambda/latest/dg/config-rs-write-functions.html)?

For example:

```js
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';

export const echo = awslambda.streamifyResponse(async (event, responseStream, _context) => {
  // As an example, convert event to a readable stream.
  const requestStream = Readable.from(Buffer.from(JSON.stringify(event)));

  await pipeline(requestStream, responseStream);
});
```

Over the next couple weeks we'll add support for this API to the Event Handler package, so depending on whether LLRT supports the APIs, it might break.

Additionally, I'd encourage LLRT to add support for `AsyncLocalStorage` from `async_hooks`; even for Logger & Metrics (core utilities) we'll most likely start using this API in the next couple months to allow for future use cases.

There's even a new package called `@aws/lambda-invoke-store` ([repo](https://github.com/awslabs/aws-lambda-invoke-store)) that, quoting its readme "is designed to be integrated with the AWS Lambda Node.js Runtime Interface Client (RIC)", which means applications targeting versions of Node.js managed runtimes that use this package, might rely on `AsyncLocalStorage` and not work on LLRT.

**Comment by nabetti1720** [comment]
@dreamorosi @perpil Thank you for providing valuable information. We would like to inform you of the current situation on the LLRT side.

- Response Streaming
   This has already been flagged as an enhancement issue ([here](https://github.com/awslabs/llrt/issues/318)). Furthermore, `awslambda.streamifyResponse()` is used by [several well-known libraries](https://github.com/awslabs/llrt/issues/318#issuecomment-3309962645), so it seems like a challenge worth addressing in order to broaden its use cases.
   On the other hand, for compatibility reasons, I also tested a workaround using `lambda-stream`, but this also caused [problems](https://github.com/awslabs/llrt/issues/1158).  

- AsyncLocalStorage
    This hasn't been raised as an issue yet.
    I was the initial implementor of LLRT's `async_hooks` module, but it was extremely extensive and difficult, requiring things like having the QuickJS side implement a V8-compatible PromiseHook API. I knew about `AsyncLocalStorage` but didn't make any progress on the implementation because I wanted to work on other things.
    Now that we have confirmed that there is demand, we will first take up the [issue](https://github.com/awslabs/llrt/issues/1170).

**Comment by dreamorosi** [comment]
Seeing as there hasn't been any significant update to LLRT in almost a year, we're closing this issue as not planned.

Support for LLRT is to be considered as best effort given its experimental nature.
