### ISSUE TITLE
Bug: Dynamic require error with ESM functions

### ISSUE THREAD

**Issue by lukehedger** [aws-powertools/powertools-lambda-typescript#2290]
### Expected Behaviour

ESM Lambda function with Tracer enabled should be invoked without error

### Current Behaviour

Lambda invocation error received:

```
{
  "errorType": "Error",
  "errorMessage": "Dynamic require of \"util\" is not supported",
  "trace": [
    "Error: Dynamic require of \"util\" is not supported",
    "    at file:///var/task/index.mjs:1:382",
    "    at <anonymous> (/node_modules/cls-hooked/context.js:4:14)",
    "    at file:///var/task/index.mjs:1:458",
    "    at <anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:5:11)",
    "    at file:///var/task/index.mjs:1:458",
    "    at <anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/aws-xray.js:2:20)",
    "    at file:///var/task/index.mjs:1:458",
    "    at <anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/index.js:3:18)",
    "    at file:///var/task/index.mjs:1:458",
    "    at <anonymous> (/node_modules/@aws-lambda-powertools/tracer/lib/esm/provider/ProviderService.js:1:21)"
  ]
}
```

### Code snippet

Lambda function with following configuration in CDK app (some options removed for brevity):

```ts
new NodejsFunction(this, "MyFunction", {
  architecture: Architecture.ARM_64,
  bundling: {
    format: OutputFormat.ESM,
  },
  runtime: Runtime.NODEJS_20_X,
  tracing: Tracing.ACTIVE,
})
```

### Steps to Reproduce

1. Deploy an ESM Lambda function with Tracer
2. Invoke function
3. Observe error

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by lukehedger** [comment]
Thanks Andrea - missed this in the docs, works fine now!
